Improve deployment script a little (still no CD).

diff --git a/modules/apps/templates/failmap-deploy.erb b/modules/apps/templates/failmap-deploy.erb
--- a/modules/apps/templates/failmap-deploy.erb
+++ b/modules/apps/templates/failmap-deploy.erb
@@ -1,8 +1,19 @@
 #!/bin/bash
 
-set -xe
+# exit on every error
+set -e
 
 image="<%= @image %>"
+
+function rollback {
+  /usr/bin/docker tag "${image/latest/rollback}" "${image}"
+  systemctl restart docker-failmap-admin.service
+  exit 1
+}
+trap "rollback" SIGINT
+
+# show every executed step
+set -x
 
 # save current image as rollback
 /usr/bin/docker tag "${image}" "${image/latest/rollback}"
@@ -13,5 +24,20 @@ image="<%= @image %>"
 # migrate database
 /usr/local/bin/failmap-admin migrate
 
-# restart all related services
+# restart admin
+systemctl restart docker-failmap-admin.service
+
+set +x
+echo
+echo "Admin restarted, please verify and press [enter] to continue deploy or [ctrl-c] to rollback."
+echo
+echo "https://admin.faalkaart.nl/"
+echo
+echo "Please not it might take a few seconds for backend to be available and 502 error to disappear."
+echo
+set -x
+# wait for user input
+read -r
+
+# restart all services
 systemctl restart docker-failmap-*.service
